version: "3.3"

services:
  database_default:
    container_name: database_default
    image: postgres
    restart: always
    volumes:
      - ./.pgdata_1:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=default
    ports:
      - "5433:5432"

  database_users:
    container_name: database_users
    image: postgres
    restart: always
    volumes:
      - ./.pgdata_2:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
      - POSTGRES_DB=users
    ports:
      - "5434:5432"
